In [1]:
import numpy as np

unif_random_matrix = np.random.uniform(0., 1., size = [2,2])

In [2]:
unif_random_matrix

array([[0.00982512, 0.35406431],
       [0.83478423, 0.22576863]])

In [6]:
binary_random_matrix = 1*(unif_random_matrix < 0.8)

In [11]:
binary_random_matrix

array([[1, 1],
       [0, 1]])

In [9]:
data_x = np.random.uniform(1, 10, size = [2,2])

In [10]:
data_x

array([[4.28064816, 6.93133614],
       [6.16517995, 5.42266971]])

In [12]:
miss_data_x = data_x.copy()
miss_data_x[binary_random_matrix == 0] = np.nan

In [13]:
miss_data_x

array([[4.28064816, 6.93133614],
       [       nan, 5.42266971]])

In [14]:
1-np.isnan(miss_data_x)

array([[1, 1],
       [0, 1]])

In [15]:
data_x = miss_data_x

In [16]:
data_m = 1-np.isnan(data_x)

# System parameters
batch_size = 128
hint_rate = 0.9
alpha = 100
iterations = 10

# Other parameters
no, dim = data_x.shape

# Hidden state dimensions
h_dim = int(dim)

In [18]:
from utils import normalization, renormalization, rounding
from utils import xavier_init
from utils import binary_sampler, uniform_sampler, sample_batch_index

In [20]:
data = data_x
_, dim = data.shape
norm_data = data.copy()

# MixMax normalization
min_val = np.zeros(dim)
max_val = np.zeros(dim)

# For each dimension
for i in range(dim):
    min_val[i] = np.nanmin(norm_data[:,i])
    norm_data[:,i] = norm_data[:,i] - np.nanmin(norm_data[:,i])
    max_val[i] = np.nanmax(norm_data[:,i])
    norm_data[:,i] = norm_data[:,i] / (np.nanmax(norm_data[:,i]) + 1e-6)   

# Return norm_parameters for renormalization
norm_parameters = {'min_val': min_val,
                 'max_val': max_val}

In [21]:
norm_data

array([[0.        , 0.99999934],
       [       nan, 0.        ]])

In [22]:
norm_parameters

{'min_val': array([4.28064816, 5.42266971]),
 'max_val': array([0.        , 1.50866644])}

In [26]:
idx = np.random.permutation(10)

In [28]:
idx

array([4, 9, 1, 5, 0, 2, 8, 6, 3, 7])

In [27]:
idx[:2]

array([4, 9])